import "./globals.css";
import { Lato } from "next/font/google";
import Providers from "./providers";
import { headers } from "next/headers";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className={lato.className}>
      <body className="bg-bone-700">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
